on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            examples/express/package-lock.json
            examples/azure-functions/package-lock.json

      - run: npm ci
        working-directory: .

      - run: npm run build
        working-directory: .

      - run: npm ci
        working-directory: ./examples/express

      - run: npm ci
        working-directory: ./examples/azure-functions

      - run: npm run lint
        working-directory: .

      - run: npm run test
        working-directory: .
