name: Release

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            examples/express/package-lock.json

      - run: npm ci
        working-directory: .

      - run: npm run build
        working-directory: .
        
      - run: npm ci
        working-directory: ./examples/express

      - run: npm ci
        working-directory: ./examples/azure-functions

      - run: npm run lint
        working-directory: .

      - run: npm run test
        working-directory: .

      # Exclude unnecessary files from being published to npm
      - run: |
          rm -rf .github
          rm -rf .husky
          rm -rf .vscode
          rm -rf examples
          rm -rf tests
          rm biome*
          rm commitlint
          rm vitest*

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

